In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('dataRawHeaders.csv')

# rename columns with underscores replaced by spaces
data = data.rename(columns=lambda x: x.replace('_', ' '))

# convert date column to datetime format
data['Date'] = pd.to_datetime(data['Date'].astype(str), format='%Y%m%d')
data

,Date,Game Number,Day of Week,Visiting Team,Visiting League,Visiting Team Game Number,Home Team,Home League,Home Team Game Number,Visiting Team Score,...,home starting player7 name,home starting player7 defensive position,home starting player8 ID,home starting player8 name,home starting player8 defensive position,home starting player9 ID,home starting player9 name,home starting player9 defensive position,additional information,acquisition information
0,2022-04-07,0,Thu,SDN,NL,1,ARI,NL,1,2,...,Seth Beer,10,ellid002,Drew Ellis,5,perdg001,Gerardo Perdomo,6,NaN,Y
1,2022-04-07,0,Thu,CIN,NL,1,ATL,NL,1,6,...,Travis d'Arnaud,2,dicka001,Alex Dickerson,10,swand001,Dansby Swanson,6,NaN,Y
2,2022-04-07,0,Thu,MIL,NL,1,CHN,NL,1,4,...,Jason Heyward,8,wisdp001,Patrick Wisdom,5,hoern001,Nico Hoerner,6,NaN,Y
3,2022-04-07,0,Thu,PIT,NL,1,SLN,NL,1,0,...,Yadier Molina,2,badeh001,Harrison Bader,8,edmat001,Tommy Edman,4,NaN,Y
4,2022-04-07,0,Thu,NYN,NL,1,WAS,NL,1,5,...,Maikel Franco,5,escoa003,Alcides Escobar,6,roblv001,Victor Robles,8,NaN,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2425,2022-10-05,0,Wed,KCA,AL,162,CLE,AL,162,2,...,Will Brennan,7,maill001,Luke Maile,2,stram002,Myles Straw,8,NaN,Y
2426,2022-10-05,0,Wed,PHI,NL,162,HOU,AL,162,2,...,Jake Meyers,8,dubom001,Mauricio Dubon,6,maldm001,Martin Maldonado,2,NaN,Y
2427,2022-10-05,0,Wed,ANA,AL,162,OAK,AL,162,2,...,Conner Capel,9,garcd004,Dermis Garcia,3,allen002,Nick Allen,6,NaN,Y
2428,2022-10-05,0,Wed,DET,AL,162,SEA,AL,162,4,...,Abraham Toro,5,casac001,Curt Casali,2,crawj002,J.P. Crawford,6,NaN,Y
2429,2022-10-05,0,Wed,NYA,AL,162,TEX,AL,162,2,...,Charlie Culberson,7,tavel001,Leody Taveras,8,thomb003,Bubba Thompson,9,NaN,Y

In [2]:
scores = data.copy()
scores = scores[['Date','Visiting Team', 'Home Team','Visiting Team Score','Home Team Score']]
scores['Home Diff'] = scores['Home Team Score'] - scores['Visiting Team Score']
scores['Home Win'] = scores['Home Diff'] > 0
scores['Home Win'].sum()/scores.shape[0]

0.5333333333333333

In [3]:
scores['Home Diff'].describe()

count    2430.000000
mean        0.067078
std         4.402929
min       -23.000000
25%        -3.000000
50%         1.000000
75%         3.000000
max        21.000000
Name: Home Diff, dtype: float64

In [4]:
data.to_csv('baseball.csv',index=False)